In [2]:
import pandas as pd
import numpy as np

# Task 1

def answer_one():
    # Load Energy Indicators data
    energy_file = "data/Energy Indicators test.xlsx"
    energy = pd.read_excel(energy_file, skiprows=1, engine="openpyxl")
    
    # Drop the first unnamed column (duplicate country names)
    energy = energy.iloc[:, 1:]
    
    # Rename columns
    energy.columns = ['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable']
    
    # Convert 'Energy Supply' to gigajoules (1 petajoule = 1,000,000 gigajoules)
    energy['Energy Supply'] = pd.to_numeric(energy['Energy Supply'], errors='coerce') * 1e6
    energy['Energy Supply per Capita'] = pd.to_numeric(energy['Energy Supply per Capita'], errors='coerce')
    energy['% Renewable'] = pd.to_numeric(energy['% Renewable'], errors='coerce')
    
    # Rename specific countries
    country_replacements = {
        "Republic of Korea": "South Korea",
        "United States of America": "United States",
        "United Kingdom of Great Britain and Northern Ireland": "United Kingdom",
        "China, Hong Kong Special Administrative Region": "Hong Kong"
    }
    
    # Remove numbers and text inside parentheses
    energy['Country'] = energy['Country'].replace(country_replacements, regex=True)
    energy['Country'] = energy['Country'].str.replace(r" \(.*\)", "", regex=True)
    energy['Country'] = energy['Country'].str.replace(r"\d+", "", regex=True)
    
    # Load GDP data
    gdp_file = "data/API_NY.GDP.MKTP.CD_DS2_en_csv_v2_76261.csv"
    gdp_raw = pd.read_csv(gdp_file, skiprows=4)
    
    gdp_replacements = {
        "Korea, Rep.": "South Korea",
        "Iran, Islamic Rep.": "Iran",
        "Hong Kong SAR, China": "Hong Kong"
    }
    
    gdp_raw.rename(columns={"Country Name": "Country"}, inplace=True)
    gdp_raw["Country"] = gdp_raw["Country"].replace(gdp_replacements)
    
    gdp_columns = ["Country"] + [str(year) for year in range(2006, 2016)]
    gdp = gdp_raw[gdp_columns]
    
    # Load ScimEn data
    scimen_file = "data/scimagojr country rank 1996-2023 (1).xlsx"
    scimen = pd.read_excel(scimen_file, sheet_name=0, engine="openpyxl")
    scimen = scimen[['Country', 'Rank', 'Documents', 'Citable documents', 'Citations', 
                     'Self-citations', 'Citations per document', 'H index']]
    
    # Select only top 15 countries by rank
    scimen_top15 = scimen[scimen['Rank'] <= 15]
    
    # Merge datasets
    merged_df = pd.merge(energy, gdp, on="Country", how="inner")
    final_df = pd.merge(merged_df, scimen_top15, on="Country", how="inner")
    
    # Set 'Country' as the index
    final_df.set_index('Country', inplace=True)
    
    # Select final columns
    final_columns = ['Rank', 'Documents', 'Citable documents', 'Citations', 'Self-citations',
                     'Citations per document', 'H index', 'Energy Supply', 'Energy Supply per Capita', '% Renewable'] + \
                    [str(year) for year in range(2006, 2016)]
    final_df = final_df[final_columns]

    # Sort by 'Rank' column in ascending order
    final_df = final_df.sort_values(by='Rank', ascending=True)
    
    return final_df

# Run the function to check output
data_result = answer_one()

# Display the result
from IPython.display import display
display(data_result)

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,% Renewable,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
Country,,,,,,,,,,,,,,,,,,,,
China,1,402188,400158,5077232,3511673,12.62,343,1.271910e+11,93.0,19.754910,2.752119e+12,3.550328e+12,4.594337e+12,5.101691e+12,6.087192e+12,7.551546e+12,8.532185e+12,9.570471e+12,1.047562e+13,1.106157e+13
United States,2,208042,203356,3540288,1004877,17.02,458,9.083800e+10,286.0,11.570980,1.381558e+13,1.447423e+13,1.476986e+13,1.447807e+13,1.504897e+13,1.559973e+13,1.625397e+13,1.688068e+13,1.760814e+13,1.829502e+13
India,3,81853,79757,968523,369256,11.83,237,3.319500e+10,26.0,14.969080,9.402599e+11,1.216736e+12,1.198895e+12,1.341888e+12,1.675616e+12,1.823052e+12,1.827638e+12,1.856722e+12,2.039126e+12,2.103588e+12
Japan,4,58342,57735,717946,154848,12.31,228,1.898400e+10,149.0,10.232820,4.601663e+12,4.579751e+12,5.106679e+12,5.289493e+12,5.759072e+12,6.233147e+12,6.272363e+12,5.212328e+12,4.896994e+12,4.444931e+12
United Kingdom,5,56288,54713,1095371,179764,19.46,293,7.920000e+09,124.0,10.600470,2.708442e+12,3.090510e+12,2.929412e+12,2.412840e+12,2.485483e+12,2.663806e+12,2.707090e+12,2.784854e+12,3.064708e+12,2.927911e+12
Germany,6,50906,49773,777362,160302,15.27,252,1.326100e+10,165.0,17.901530,3.046309e+12,3.484057e+12,3.808786e+12,3.479801e+12,3.468154e+12,3.824829e+12,3.597897e+12,3.808086e+12,3.965801e+12,3.423568e+12
Russian Federation,7,46186,45868,217996,96688,4.72,112,3.070900e+10,214.0,17.288680,9.899321e+11,1.299703e+12,1.660848e+12,1.222646e+12,1.524917e+12,2.045923e+12,2.208294e+12,2.292470e+12,2.059242e+12,1.363482e+12
Canada,8,41209,40390,915491,142691,22.22,284,1.043100e+10,296.0,61.945430,1.319265e+12,1.468820e+12,1.552990e+12,1.374625e+12,1.617343e+12,1.793327e+12,1.828366e+12,1.846597e+12,1.805750e+12,1.556509e+12
Italy,9,38700,36909,639473,147302,16.52,209,6.530000e+09,109.0,33.667230,1.958564e+12,2.222524e+12,2.417508e+12,2.209484e+12,2.144936e+12,2.306974e+12,2.097929e+12,2.153226e+12,2.173256e+12,1.845428e+12
South Korea,10,38362,38046,618762,105419,16.13,198,1.100700e+10,221.0,2.279353,1.053217e+12,1.172614e+12,1.047339e+12,9.439419e+11,1.143672e+12,1.253290e+12,1.278047e+12,1.370633e+12,1.484489e+12,1.466039e+12
Iran,11,32080,31725,634135,177894,19.77,198,9.172000e+09,119.0,5.707721,2.656022e+11,3.497366e+11,4.060709e+11,4.140591e+11,4.870696e+11,6.290823e+11,6.440193e+11,5.003998e+11,4.622848e+11,4.091917e+11
France,12,30810,30139,547122,89958,17.76,221,1.059700e+10,166.0,17.020280,2.317862e+12,2.655817e+12,2.926803e+12,2.700076e+12,2.646230e+12,2.870409e+12,2.683007e+12,2.816078e+12,2.861236e+12,2.442483e+12
Spain,13,29840,29156,614087,104845,20.58,216,4.923000e+09,106.0,37.968590,1.261847e+12,1.476746e+12,1.636115e+12,1.496588e+12,1.427989e+12,1.487569e+12,1.330995e+12,1.362187e+12,1.380245e+12,1.206165e+12
Australia,14,27993,27254,608021,84747,21.72,234,5.386000e+09,231.0,11.810810,7.484176e+11,8.550075e+11,1.056112e+12,9.287621e+11,1.148838e+12,1.398611e+12,1.547532e+12,1.577123e+12,1.468265e+12,1.351296e+12
Brazil,15,27316,26888,307607,71778,11.26,154,1.214900e+10,59.0,69.648030,1.107627e+12,1.397114e+12,1.695855e+12,1.666996e+12,2.208838e+12,2.616156e+12,2.465228e+12,2.472820e+12,2.456044e+12,1.802212e+12

In [3]:
# Task 2

import pandas as pd

def answer_two():
    # Get the table from Question 1
    Top15 = answer_one()
    
    # Calculate the average GDP over 10 years (2006-2015)
    avgGDP = Top15.loc[:, '2006':'2015'].mean(axis=1)
    
    # Sort in descending order
    avgGDP = avgGDP.sort_values(ascending=False)

    return avgGDP

# Function call
avgGDP_result = answer_two()
display(answer_two())

Country
United States         1.572243e+13
China                 6.927707e+12
Japan                 5.239642e+12
Germany               3.590729e+12
United Kingdom        2.777505e+12
France                2.692000e+12
Italy                 2.152983e+12
Brazil                1.988889e+12
Russian Federation    1.666746e+12
Canada                1.616359e+12
India                 1.602352e+12
Spain                 1.406644e+12
South Korea           1.221328e+12
Australia             1.207997e+12
Iran                  4.567516e+11
dtype: float64

In [4]:
# Task 3

def answer_three():
    # Get the table from Question 1
    Top15 = answer_one()
    
    # Get the 6th country by average GDP
    avgGDP = answer_two()
    country = avgGDP.index[5]  # Extract the country from the index
    
    # Retrieve GDP for 2006 and 2015
    gdp_2006 = Top15.loc[country, '2006']
    gdp_2015 = Top15.loc[country, '2015']
    
    # Calculate GDP change over the 10-year period
    gdp_change = gdp_2015 - gdp_2006
    
    return gdp_change

# Function call
print(answer_three())

124621907951.68018

In [5]:
# Task 4

def answer_four():
    # Get the table from Question 1
    Top15 = answer_one()
    
    # Add the "Citation Ratio" column
    Top15["Citation Ratio"] = Top15["Self-citations"] / Top15["Citations"]
    
    # Find the country with the highest ratio
    max_country = Top15["Citation Ratio"].idxmax()
    max_ratio = Top15["Citation Ratio"].max()
    
    return (max_country, max_ratio)  # Keep as float but avoid np.float64 label

# Function call
country, ratio = answer_four()
print(f"{country}: {ratio:.15f}")

China: 0.691651080746359

In [6]:
# Task 5

def answer_five():
    # Get the DataFrame from Question 1
    Top15 = answer_one()
    
    # Add the "Estimated Population" column (Energy Supply / Energy Supply per Capita)
    Top15["Estimated Population"] = Top15["Energy Supply"] / Top15["Energy Supply per Capita"]
    
    # Find the third most populous country
    third_most_populous = Top15["Estimated Population"].nlargest(3)
    
    # Extract the country name
    country_name = third_most_populous.idxmin()
    
    return country_name  # Return only the country name

# Function call, Output country name
print(answer_five())

United States

In [7]:
# Task 6

def answer_six():
    # Get the table from Question 1
    Top15 = answer_one()
    
    # Add the "Estimated Population" column
    Top15["Estimated Population"] = Top15["Energy Supply"] / Top15["Energy Supply per Capita"]
    
    # Add the "Citable docs per person" column
    Top15["Citable docs per person"] = Top15["Citable documents"] / Top15["Estimated Population"]
    
    # Compute the correlation between "Citable docs per person" and "Energy Supply per Capita"
    correlation = Top15["Citable docs per person"].corr(Top15["Energy Supply per Capita"])
    
    return correlation

# Function call
print(answer_six())

0.7019601723071188

In [8]:
# Task 7

def answer_seven():
    # Get the table from Question 1
    Top15 = answer_one()
    
    # Add the "Estimated Population" column
    Top15["Estimated Population"] = Top15["Energy Supply"] / Top15["Energy Supply per Capita"]
    
    # Define the continent mapping dictionary
    ContinentDict = {
        'China': 'Asia', 
        'United States': 'North America', 
        'Japan': 'Asia', 
        'United Kingdom': 'Europe', 
        'Russian Federation': 'Europe', 
        'Canada': 'North America', 
        'Germany': 'Europe', 
        'India': 'Asia',
        'France': 'Europe', 
        'South Korea': 'Asia', 
        'Italy': 'Europe', 
        'Spain': 'Europe', 
        'Iran': 'Asia',
        'Australia': 'Australia', 
        'Brazil': 'South America'
    }
    
    # Add the "Continent" column
    Top15["Continent"] = Top15.index.map(ContinentDict)
    
    # Group by continent and compute statistics
    result = Top15.groupby("Continent")["Estimated Population"].agg(["size", "sum", "mean", "std"])
    result.fillna(0, inplace=True)
    return result  # Return the resulting table

# Function call
answer_seven()

               size           sum          mean           std
Continent
Asia              5  2.898666e+09  5.797333e+08  6.790979e+08
Australia         1  2.331602e+07  2.331602e+07  0.000000e+00
Europe            6  4.579297e+08  7.632161e+07  3.464767e+07
North America     2  3.528552e+08  1.764276e+08  1.996696e+08
South America     1  2.059153e+08  2.059153e+08  0.000000e+00